build:
  image: chikim/rails5_skeleton # TODO fix
  environment:
    REPO_URL: git@github.com:globis-org/glopla_admin.git
    EMAIL_USERNAME: sample@sample.com
    EMAIL_PASSWORD: sample1
    HOST: localhost:3000
    AWS_REGION: ap-northeast-1
    AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
    S3_BUCKET_NAME: S3_BUCKET_NAME
    DATABASE_HOSTNAME: 127.0.0.1
    DATABASE_NAME: glopla_admin
    DATABASE_USERNAME: test
    DATABASE_PASSWORD: test
    REDIS_HOSTNAME: localhost
    RAILS_ENV: test
    SECRET_KEY_BASE: ci_test
    DEVISE_SECRET_KEY: ci_test
    WEB_SERVER: unicorn
    NUM_UNICORN_WORKERS: 3
  commands:
    - framgia-ci test-connect 127.0.0.1 3306
    - bundle install
    - framgia-ci run

cache:
  mount:
    - .git
