build:
  image: banlv54/glopla_admin
  environment:
    REPO_URL: git@github.com:globis-org/glopla_admin.git
    EMAIL_USERNAME: sample@sample.com
    EMAIL_PASSWORD: sample1
    HOST: localhost:3000
    AWS_REGION: ap-northeast-1
    AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
    S3_BUCKET_NAME: S3_BUCKET_NAME
    DATABASE_HOSTNAME: 127.0.0.1
    DATABASE_NAME: glopla_admin
    DATABASE_USERNAME: test
    DATABASE_PASSWORD: test
    REDIS_HOSTNAME: localhost
    RAILS_ENV: test
    SECRET_KEY_BASE: ci_test
    DEVISE_SECRET_KEY: ci_test
    WEB_SERVER: unicorn
    NUM_UNICORN_WORKERS: 3
  commands:
    - framgia-ci test-connect 127.0.0.1 3306
    - bundle install
    - framgia-ci run

compose:
  database:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
    image: mysql
    environment:
      MYSQL_DATABASE: glopla_admin
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root

cache:
  mount:
    - .git

deploy:
  ssh:
    host: 172.16.200.52
    user: deploy
    commands:
      - export PATH="$PATH:$HOME/.rvm/bin:$HOME/deploy_bin"
      - source /home/deploy/.bash_profile
      - source /home/deploy/.env
      - localdeploy branch master
    when:
      branch: master
